- name: Upload local settings
  template:
    src: local_settings.py.j2
    dest: "{{ django_local_settings }}"
  notify:
    - reload gunicorn

- name: Run migrations
  django_manage:
    command: migrate
    app_path: "{{ django_app_dir }}"
    virtualenv: "{{ venv }}"
  notify:
    - reload gunicorn

- name: Run additional manage.py tasks
  django_manage:
    command: "{{ item }}"
    app_path: "{{ django_app_dir }}"
    virtualenv: "{{ venv }}"
  with_items: "{{ django_manage_commands }}"
