- name: Create primary gunicorn group
  group:
    name: "{{ gunicorn_group_primary }}"
  when: gunicorn_group_primary != ''

- name: Create other groups for gunicorn user
  group:
    name: "{{ item }}"
  with_items: "{{ gunicorn_groups }}"
  when: gunicorn_groups != []

- name: Create gunicorn user
  user:
    name: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group_primary or omit }}"
    groups: "{{ gunicorn_groups | join(',') or omit }}"
    createhome: no
