- name: Create log directory
  become: yes
  file:
    path: "{{ django_log_file | dirname }}"
    state: directory
    owner: "{{ gunicorn_user }}"
    mode: 0755
  when: django_log_file != ''

- name: Get log file information
  stat:
    path: "{{ django_log_file }}"
  register: log_file_info
  when: django_log_file != ''

- name: Ensure log file exists
  become: yes
  file:
    mode: 0644
    owner: "{{ gunicorn_user }}"
    path: "{{ django_log_file }}"
    state: touch
  when: django_log_file != '' and not log_file_info.stat.exists

- name: Upload local settings
  template:
    src: local_settings.py.j2
    dest: "{{ django_local_settings }}"
    owner: "{{ gunicorn_user }}"
    mode: 0400
  notify:
    - reload gunicorn

- name: Run migrations
  environment: "{{ gunicorn_environment }}"
  django_manage:
    command: migrate
    app_path: "{{ django_app_dir }}"
    settings: "{{ django_settings_module }}"
    virtualenv: "{{ venv }}"
  notify:
    - reload gunicorn

- name: Run additional manage.py tasks
  environment: "{{ gunicorn_environment }}"
  django_manage:
    command: "{{ item }}"
    app_path: "{{ django_app_dir }}"
    settings: "{{ django_settings_module }}"
    virtualenv: "{{ venv }}"
  with_items: "{{ django_manage_commands }}"
