- name: Create log directory
  become: yes
  file:
    path: "{{ django_log_file | dirname }}"
    state: directory
    owner: "{{ gunicorn_user }}"
    mode: 0755
    recurse: yes
  when: django_log_file != ''

- name: Upload local settings
  template:
    src: local_settings.py.j2
    dest: "{{ django_local_settings }}"
    owner: "{{ gunicorn_user }}"
    mode: 0400
  notify:
    - reload gunicorn

- name: Run migrations
  django_manage:
    command: migrate
    app_path: "{{ django_app_dir }}"
    settings: "{{ django_settings_module }}"
    virtualenv: "{{ venv }}"
  notify:
    - reload gunicorn

- name: Run additional manage.py tasks
  django_manage:
    command: "{{ item }}"
    app_path: "{{ django_app_dir }}"
    settings: "{{ django_settings_module }}"
    virtualenv: "{{ venv }}"
  with_items: "{{ django_manage_commands }}"
